site:
  url: https://solar-forecast.dinghy.dev
  baseUrl: /
  title: Solar Forecast
  favicon: assets/favicon.svg
  headTags:
    - tagName: link
      attributes:
        rel: apple-touch-icon
        href: /assets/apple-touch-icon.png
    - tagName: meta
      attributes:
        name: apple-mobile-web-app-title
        content: Solar Forecast
    - tagName: meta
      attributes:
        name: apple-mobile-web-app-capable
        content: 'yes'
    - tagName: meta
      attributes:
        name: mobile-web-app-capable
        content: 'yes'
  navbar:
    title: Solar Forecast
    logo:
      src: /assets/favicon.svg
      href: https://solar-forecast.dinghy.dev/
      target: _self
    items:
      - type: custom-locationControl
        position: right
      - href: https://github.com/dinghydev/solar-forecast
        label: GitHub
        position: right
        className: header-github-link
        aria-label: GitHub repository
  footer: false
